### ISSUE TITLE
I am getting "No managed object model found" exception.

### ISSUE THREAD

**Issue by shannoga** [MarcoSero/Nimble#16]
Hi,
Just migrated my app from Magical Record (Wanted to use your iCloud capabilities).
I am using 
```
        NSError *error;
        [NimbleStore nb_setupCloudStore:&error];
```
And get this exception

```
 if (error || !persistentStore) {
    NSString *errorMessage = @"No managed object model found.";
    NBLog(errorMessage, nil);
    if (error != NULL) {
      *error = [NSError errorWithDomain:NBNimbleErrorDomain code:NBNimbleErrorCode userInfo:@{@"error" : errorMessage}];
    }
#ifdef DEBUG
    @throw ([NSException exceptionWithName:NBPersistentStoreException reason:errorMessage userInfo:nil]);
#endif
    return NO;
  }
```

1. I think the error description is wrong as I already have a model at this point.
2. I can see that I have a persistentStore too so I think that somehow I am getting an other error from the 'addPersistentStoreWithType' method.
3. this is the error that I get : 

```
(NSError **) error = 0xbfffcbe4 error: summary string parsing error

```

Can any one point me to th problem ?
Thanks
Shani

**Comment by khaledannajar** [comment]
In Xcode 6 there is no PCH files anymore. How this can be fixed?

**Comment by khaledannajar** [comment]
I found a check to a pointer to error object in class **NimbleStore.m** in line 108
from
```
if (error || !persistentStore) {
```
to *error
```
if (*error || !persistentStore) {
```
and it passed. I don't know if this is valid or not.

**Comment by MarcoSero** [comment]
@khaledannajar that's definitely a bug. Thanks for finding it and feel free to open a PR with the fix :+1:

**Comment by khaledannajar** [comment]
@MarcoSero Sorry, I don't think this is the fix. I may not be understanding pointers well. I tried to run the unit test and they failed.

**Comment by MarcoSero** [comment]
The code right now is definitely wrong, I pushed a fix https://github.com/MarcoSero/Nimble/commit/989d8d9eef04b49c94b1c6d03422ac5f962a1768

As for the error "summary string parsing error", that's an LLDB error trying to print the description of a double pointer.

**Comment by khaledannajar** [comment]
Thanks. It works now. :+1:
