### ISSUE TITLE
Difference between NBMainContext and NBBackgroundContext

### ISSUE THREAD

**Issue by appcelerate** [MarcoSero/Nimble#28]
Whats the functional difference between them?
I dont understand this

**Comment by MarcoSero** [comment]
I'd recommend reading http://www.cocoanetics.com/2012/07/multi-context-coredata/

**Comment by appcelerate** [comment]
@MarcoSero so then 
```Objective-C
[NSObject nb_createInContextOfType:NBMainContext];
```
is for Local Context

and 

```Objective-C
[NSObject nb_createInContextOfType:NBBackgroundContext];
```
is for iCloud Context?
