### ISSUE TITLE
iCloud Sync Problems

### ISSUE THREAD

**Issue by appcelerate** [MarcoSero/Nimble#29]
If i try to save an Object like

```
[NimbleStore nb_saveInBackground:^(NBContextType contextType) {
      Object *object = [Object nb_createInContextOfType:contextType];
      [car setName:name];
} completion:^(NSError *error) {
        NSLog(@"ERROR %@", error);
    }];
```

The Error is nil. 
Then i start the App on an other Device(Simulator with Signing in at iCloud) and try to find the savedObject i find nothing.

```
[Object nb_findAll] 
```

always nil.

I used this Init Method

```
NSError *error;
[NimbleStore nb_setupCloudStore:&error];
```

**Comment by MarcoSero** [comment]
I can see a lot of things that can possibly go wrong in this scenario (entitlements, provisioning profiles, time for iCloud to propagate the changes).
This is just a wrapper around Apple's Core Data and iCloud capabilities.

**Comment by appcelerate** [comment]
why i get problems with the prov. profiles.

The Problem is, i get nothing at the other Device, no Data via iCloud. 
This was my question :)
